version: 2.1
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk@sha256:4c5a50b499f1ef5b30fb5941c31822bb561afa3fb6b9fdb6f1db55d6f6be3a95
    steps:
      - checkout
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          cd go.opentelemetry.io
          chmod 755 deploy.sh
          ./deploy.sh

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
