version: 2.1
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk@sha256:0c954088addbae0b00dbacc1505ea7616ff4496d1a281c9bae9589b3c4aa25ac
    steps:
      - checkout
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          cd go.opentelemetry.io
          chmod 755 deploy.sh
          ./deploy.sh

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
