version: 2.1
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk@sha256:18591374c79cd9f589a967298207cb8f34a0d4fa3a10c74fa06543920fb74d61
    steps:
      - checkout
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          cd go.opentelemetry.io
          chmod 755 deploy.sh
          ./deploy.sh

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
