name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: $GCLOUD_SERVICE_KEY

      - uses: google-github-actions/setup-gcloud@v2

      - uses: actions/checkout@v4

      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          cd go.opentelemetry.io
          chmod 755 deploy.sh
          ./deploy.sh
